In [1]:
import torch
import numpy as np

TENSORS

In [2]:
# List
my_list = [[1., 2., 3., 4., 5.], [6., 7., 8., 9., 10.]]
print(type(my_list))
print("My List:", my_list)

# Array
my_array = np.random.rand(3, 4)
print(my_array.dtype)
print("My Array:", my_array)

# Tensor
my_tensor = torch.randn(3, 4)
print(my_tensor.dtype)
print("My Tensor:", my_tensor)

<class 'list'>
My List: [[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 8.0, 9.0, 10.0]]
float64
My Array: [[0.11233419 0.33450406 0.16927235 0.09435199]
 [0.64533928 0.67823199 0.2196981  0.56711676]
 [0.47659181 0.7514259  0.89222323 0.91963919]]
torch.float32
My Tensor: tensor([[-0.6727, -0.5934, -0.3486,  0.0131],
        [ 1.0783, -0.2363, -0.4034,  0.2332],
        [-0.8681,  0.0326, -1.4116,  0.8766]])


TENSOR OPERATIONS

In [3]:
my_tensor = torch.arange(10)
my_tensor                   

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape
my_tensor = my_tensor.reshape(2, 5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
# Reshape with -1
my_tensor2 = torch.arange(10)
my_tensor2 = my_tensor2.reshape(2, -1)
my_tensor2 

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# View (similar to Reshape)
my_tensor3 = torch.arange(10)
my_tensor3 = my_tensor3.view(2, 5)
my_tensor3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# Slices
my_tensor4 = torch.arange(10)
my_tensor4[7]

tensor(7)

In [9]:
my_tensor4[1:3]

tensor([1, 2])

In [17]:
my_tensor4 = my_tensor4.reshape(5, 2)
my_tensor4
my_tensor4[:, 1]

tensor([1, 3, 5, 7, 9])

TENSOR MATH OPERATIONS

In [20]:
# Tensor Addition
tensor1 = torch.tensor([1 ,2 ,3 ,4 ,5])
tensor2 = torch.tensor([6 ,7 ,8 ,9 ,10])

In [21]:
tensor1 + tensor2

tensor([ 7,  9, 11, 13, 15])

In [22]:
torch.add(tensor1, tensor2)

tensor([ 7,  9, 11, 13, 15])

In [23]:
# Tensor Subtraction
tensor1 - tensor2

tensor([-5, -5, -5, -5, -5])

In [24]:
torch.sub(tensor1, tensor2)

tensor([-5, -5, -5, -5, -5])

In [25]:
# Tensor Multiplication
tensor1 * tensor2

tensor([ 6, 14, 24, 36, 50])

In [26]:
torch.mul(tensor1, tensor2)

tensor([ 6, 14, 24, 36, 50])

In [27]:
# Tensor Division
tensor1 / tensor2

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [28]:
torch.div(tensor1, tensor2)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [29]:
# Tensor Power
tensor1 ** 2

tensor([ 1,  4,  9, 16, 25])

In [30]:
# Tensor Exponential
torch.exp(tensor1)

tensor([  2.7183,   7.3891,  20.0855,  54.5981, 148.4132])